### ISSUE TITLE
transip provider needs requests>=2.27.0 in dependency spec

### ISSUE THREAD

**Issue by lambacck** [AnalogJ/lexicon#1099]
The update of the transip provider from #1086 included in 3.9.2 uses `from requests.exceptions import JSONDecodeError` which was first included in requests 2.27.0 but the requirements spec only requires `>=2`:
https://github.com/AnalogJ/lexicon/blob/d8b26bcfffd484f34444c91ceb3ced4a2583bd18/pyproject.toml#L43

This is passed directly through to the requirement spec in the wheel:
```
Requires-Dist: requests (>=2)
```

And means that someone who upgrades dns-lexicon from a previous version using pip will get an import error.

**Comment by adferrand** [comment]
Hello @lambacck, and thanks a lot!

Instead of requiring `2.27.0`, which is quite recent and may be problematic to resolve with other constraints for users, I prefer to fallback to the `simplejson.JSONDecodeError` and `json.JSONDecodeError` catch and just require `requests>=2`. I built #1100 for that purpose.
