### ISSUE TITLE
Lexicon providers invoke `print` directly, making it difficult for calling code to suppress or redirect output

### ISSUE THREAD

**Issue by zjs** [AnalogJ/lexicon#124]
Currently, the convention for providers is to invoke `print` directly. For code using Lexicon as a library, it would be helpful to use a pattern that allows for suppressing or redirecting output (e.g., to a log file).

Perhaps this is already possible, but I don't see a way to do so.

**Comment by AnalogJ** [comment]
Hey,
Yeah, thats actually on my list of things I wanted to fix. 
Basically using the Python [logging](https://docs.python.org/2/library/logging.html) standard module to replace all the `print` statements. 

If you can open a PR I'd be happy to merge it. Otherwise I should be able to get to this in a week or 2.
