### ISSUE TITLE
DuckDNS.org API support

### ISSUE THREAD

**Issue by stokito** [AnalogJ/lexicon#1511]
The DuckDNS.org is a popular Dynamic DNS provider. And it supports the TXT records update which is used for issuing ACME certificates. Here is a sample https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_duckdns.sh
Could you please support it's API?
Also please read the discussion [DNS API standard or specification](https://community.letsencrypt.org/t/dns-api-standard-or-specification/189887)

It also will be nice to support the https://github.com/joohoi/acme-dns/blob/master/README.md

**Comment by grcancelliere** [comment]
I'm preparing a PR for it; the API is quite simple, but since it only supports an "/update" endpoint the rest of the provider uses dnspython for all the other checks.

The main code is ready, but since I already had to skip a lot of tests due to Duck DNS not supporting many DNS features I'm working on mocking dnspython as little as possibile to have sane tests with vcrpy.
