### ISSUE TITLE
requests logging level exposes credentials

### ISSUE THREAD

**Issue by rbelnap** [AnalogJ/lexicon#174]
Currently, when using lexicon, the requests library logs every connection and request to the providers api.  I'm currently only using namecheap, which sadly includes the ApiUser and ApiKey as GET vars.  So, every use of lexicon exposes these values.  This becomes a problem, particularly when using lexicon as a library, when automated scripts expose and log these values. 

I'm not familiar with other providers, so I don't know how much of an issue this is generally.  I hope I'm just missing a switch to turn down the logging, but I can't find it if so.  I can set this in providers/namecheap.py:

logging.getLogger('requests').setLevel(logging.ERROR)

to remove the messages, but I don't know if this is appropriate, or if it warrants a wider solution.  I can see why these messages could be useful in debugging (they are debug level) but in general I don't want or need to see them.  

I don't know if there is a reason why the default logger is set to debug, but another option would be to set this higher as well.  e.g.

logging.basicConfig(stream=sys.stdout, level=logging.ERROR, format='%(message)s')

but, lots of useful output is logged at debug level (like most of the output).  What do you think?

**Comment by AnalogJ** [comment]
Hey @rbelnap 
Yeah, they are printed as debug messages, but as you mentioned there's not really a flag to configure the log level, so everything gets printed.

The best solution here would probably be to set `logging.basicConfig` dynamically via a new top level CLI flag.

https://github.com/AnalogJ/lexicon/blob/master/lexicon/__main__.py#L48
https://github.com/AnalogJ/lexicon/blob/master/lexicon/__main__.py#L64

Then the main function could look something like:
```
parsed_args = MainParser().parse_args()

log_level = logging.getLevelName(parsed_args.get('log_level','DEBUG'))

logging.basicConfig(stream=sys.stdout, level=log_level, format='%(message)s')
logger.debug('Arguments: %s', parsed_args)

```

You're correct though, eventually we'll want to ensure that the log levels throughout the codebase are consistent, so that we can set 'INFO' as the default level. 

Is adding the `log_level` CLI flag (just the first part) something you can open a PR for?

**Comment by rbelnap** [comment]
Fairly simple, since you helpfully wrote most of it!  requests INFO level is still more verbose than I'd prefer - but at least it doesn't leak secrets.  Of course, all the current logger.debug might be better off as logger.info or higher.   Most of them are displaying the fundamental output you want, which should be higher than debug.
