### ISSUE TITLE
Is certbot.default.sh still automatic?

### ISSUE THREAD

**Issue by TheGammelgalopper** [AnalogJ/lexicon#263]
Hey,
thank you for this awesome tool! It works way better than the certbot plugins and I had no headaches setting it up!

I have one question though. There is this one section in `certbot.default.sh`, where it says:

```
# Example usage (with certbot-auto and this hook file saved in /root/):
#
#   sudo ./certbot-auto -d example.org -d www.example.org -a manual -i nginx --preferred-challenges dns \
#   --manual-auth-hook "/root/certbot.default.sh auth" --manual-cleanup-hook "/root/certbot.default.sh cleanup"

```

Currently certbot is being started with just `sudo certbot`. Does it still mean that it keeps itself updated? 

Or do it need to do `certbot renew` after 90 days?

Or do I create a cron script that automatically calls the long command from above every 89 days?

**Comment by adferrand** [comment]
This script ensures only the creation of a new certificate using lexicon to insert relevant records in the dns zone.

Certificates renewal and certbot auto-update depend on what you use of certbot functionalities.

If you follow the provided example, the certbot executable will update itself, because you invoke it through certbot-auto. 

About certificates renewal, it is a different process which consists in running regularly certbot renew, which will start a renewal process with exactly the same parameters used during the certificate creation (so including the lexicon hooks).

If you installed certbot from well known distribution package manager (like apt, npm), a process is registered for you to execute the command automatically each day. If you installed certbot from sources, like with certbot-auto, you will need to add this yourself, for instance with crontab.

Please note that I have a Docker (adferrand/letsencrypt-dns) which does this, and also adds some nice automated deployment procedures.

**Comment by TheGammelgalopper** [comment]
I installed certbot with apt and started it with just `certbot`.

So `certbot renew` should then be already registered automatically if I understood correctly?

**Comment by adferrand** [comment]
Yes, very likely. Debian package should have installed a cron job, you will find it at `/etc/cron.d/certbot`. It executes `certbot renew` twice a day.

**Comment by TheGammelgalopper** [comment]
Oh good, why didn't I look into cron myself??

Yes sure, there is exactly that file which executes it twice a day (/12).

Thank you for your patience with me!
