### ISSUE TITLE
Centos 7, pip install, requests[security]

### ISSUE THREAD

**Issue by ragnarkarlsson** [AnalogJ/lexicon#335]
Hi

Trying to get Lexicon installed on Centos 7 running python 2.7.5 and pip 18.1, running into the following problem:

```
Requirement already satisfied: dns-lexicon in /usr/lib/python2.7/site-packages (3.0.7)
Requirement already satisfied: requests[security] in /usr/lib/python2.7/site-packages (from dns-lexicon) (2.6.0)
  requests 2.6.0 does not provide the extra 'security'
Requirement already satisfied: tldextract in /usr/lib/python2.7/site-packages (from dns-lexicon) (2.2.0)
Requirement already satisfied: future in /usr/lib/python2.7/site-packages (from dns-lexicon) (0.17.1)
Requirement already satisfied: cryptography in /usr/lib64/python2.7/site-packages (from dns-lexicon) (2.4.2)
Requirement already satisfied: pyyaml in /usr/lib64/python2.7/site-packages (from dns-lexicon) (3.10)
Requirement already satisfied: requests-file>=1.4 in /usr/lib/python2.7/site-packages (from tldextract->dns-lexicon) (1.4.3)
Requirement already satisfied: idna in /usr/lib/python2.7/site-packages (from tldextract->dns-lexicon) (2.7)
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from tldextract->dns-lexicon) (0.9.8)
Requirement already satisfied: enum34; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography->dns-lexicon) (1.1.6)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography->dns-lexicon) (1.9.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /usr/lib64/python2.7/site-packages (from cryptography->dns-lexicon) (1.11.5)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography->dns-lexicon) (0.24.0)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography->dns-lexicon) (1.0.16)
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography->dns-lexicon) (2.19)
```
Can't seem to find a way to resolve the request[security], any suggestions?

**Comment by stuevansuk** [comment]
Same issue here, any advice?

Traceback (most recent call last):
  File "/usr/bin/lexicon", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 794, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2735, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.6.0 has no such extra feature 'security'

**Comment by adferrand** [comment]
This error is due to the fact that you try to use pip system-wide to install Lexicon: you are exposed to interference between the python modules pre-installed as OS packages, and the ones that pip tries to install to fulfill the requirements.

In this particular test, you have `requests` module installed in version 2.6.0 as an OS package (RPM `python-requests`). Package `dns-lexicon` from pip requires `requests` to be installed, which is indeed, the case. So no upgrade is done (it is the default for pip), but this old version or requests as no `security` extra, leading to errors.

If you try to force-update requests through `pip`, replacing the OS package during that procedure, you will most likely break your Python runtime. Indeed, recent versions of `requests` will certainly have compatiblity issues with other Python modules installed as OS packages.

You have two solutions to solve this situation:
* either you install Lexicon in a Python virtual environment, to ignore all OS packages, and rely only to modules that pip will install in this virtual environment (see https://docs.python-guide.org/dev/virtualenvs/)
* either you install Lexicon also as an OS package, since Lexicon is distributed through EPEL (see https://pkgs.org/download/dns-lexicon)

**Comment by stuevansuk** [comment]
Thanks for your support, i'll look at those options!

**Comment by adferrand** [comment]
Note: I also added a summary of what I said here in the `README.md` of Lexicon.

**Comment by stuevansuk** [comment]
This is perfect and great to see it making into the Readme as it was the first place I checked when I had the issue. Cheers.
