### ISSUE TITLE
Provider easyDNS is broken

### ISSUE THREAD

**Issue by adferrand** [AnalogJ/lexicon#343]
During code refactoring to correct pylint issues, I discovered that the provider for easyDNS is broken.

Almost all cassettes registered include 5XX or 4XX HTTP errors when the provider is invoked. As the cassettes have been registered against the live API, it suggests most likely that the provider is not functional.

Tests should fail then, but a try/except block is incorrectly written, and hide all HTTP errors. https://github.com/AnalogJ/lexicon/blob/cb004f0bc5afb96533186fa017b2c766ecbc6f39/lexicon/providers/easydns.py#L54

This provider needs to be tested again against live API, fixed if needed, and new cassettes be submitted.

@AnalogJ, I assign you the issue as you are marked as the codeowner for this provider.

**Comment by yajrendrag** [comment]
appears that the problem is related to self.domain not getting set.  with --log_level DEBUG i get this:
https://rest.easydns.net:443 "PUT /zones/records/add/us.com/TXT?format=json&_user=...
(note the /zones/records/add/**us.com** is missing some of the domain name
(My root domain is of the form XXX.us.com - see 2nd problem mentioned later)

if i change this line in easydns.py:
payload = self._get('/domain/{0}'.format(self.domain))
to 
payload = self._get('/domain/{0}'.format('root.domain.name'))
it works.  i don't know enough about python classes to make a real fix.

Although there is another issue that i'm unsure is related to this provider or is more general.  

it doesn't seem to correctly parse the hostname from root domain in the case where the domain is more than 2 components, ie, more than XXX.com.  My root domain is XXX.us.com and if i submit a request for YYY.XXX.us.com, the text record gets set to:
_acme-challenge.YYY.XXX.XXX.us.com.
It should be 
_acme-challenge.YYY.XXX.us.com.

**Comment by oldium** [comment]
Wrong extraction of the root domain in form xxx.us.com is caused by the fact that tldextract during initial download of root domain registry ignores _private domain_ section. Unfortunately the domain us.com is part of this private section.

To convince the `tldextract` library to take private domains into account, there is a parameter to `TLDExtract` constructor called `include_psl_private_domains`. So I would recommend to instantiate custom `TLDExtract` class instance, supply both the `cache_file` and `include_psl_private_domains` arguments (to be sure it is not overridden by somebody else) and it will work - see https://github.com/oldium/lexicon/commit/35e09148d74cc2fc06e83db8cc699c8c9dec5c19 as a possible fix. There is a new optionally set environmental variable `LEXICON_TLDEXTRACT_CACHE` (filename to store the tldextract domain cache), which needs to be documented somewhere.
