### ISSUE TITLE
hetzner provider: (non-) optional requirements cause fail

### ISSUE THREAD

**Issue by dgrothaus-ku** [AnalogJ/lexicon#386]
The try/except block for the _optional_ requirements causes the whole provider to fail if BeautifulSoup is not installed: [Line 15](https://github.com/AnalogJ/lexicon/blob/c3dcd166663c475f66f9612eea5d77a6d529ac6e/lexicon/providers/hetzner.py#L15)

If the `bs4` module is missing, the failing import is catched and the `dns.resolver` and `dns.zone` won't be imported resulting in a non functional provider.

It took me most of a day juggling with different python versions and especially dnspython installations to finally get to this issue as the stack trace always complained about the missing dns module in [line 464]((https://github.com/AnalogJ/lexicon/blob/c3dcd166663c475f66f9612eea5d77a6d529ac6e/lexicon/providers/hetzner.py#L464)).

As the dns module is non optional, it should be listed before the `bs4` import. But as the default
table output also requires `bs4`, the whole try/except block seems to only cause trouble instead of helping because the error messages are misleading.

```
Traceback (most recent call last):
  File "/opt/lexicon_env/bin/lexicon", line 10, in <module>
    sys.exit(main())
  File "/opt/lexicon_env/lib/python3.5/site-packages/lexicon/cli.py", line 117, in main
    results = client.execute()
  File "/opt/lexicon_env/lib/python3.5/site-packages/lexicon/client.py", line 64, in execute
    self.provider.authenticate()
  File "/opt/lexicon_env/lib/python3.5/site-packages/lexicon/providers/base.py", line 69, in authenticate
    return self._authenticate()
  File "/opt/lexicon_env/lib/python3.5/site-packages/lexicon/providers/hetzner.py", line 171, in _authenticate
    with self._session(self.domain, get_zone=False):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/opt/lexicon_env/lib/python3.5/site-packages/lexicon/providers/hetzner.py", line 594, in _session
    (name if name else domain + '.'), link)
  File "/opt/lexicon_env/lib/python3.5/site-packages/lexicon/providers/hetzner.py", line 464, in _get_dns_cname
    resolver = dns.resolver.Resolver()
```

**Comment by adferrand** [comment]
Hello @dgrothaus-ku. First of all, I am very sorry that you lost so much time to understand what was wrong in your runtime environment.

Indeed, you hit an very not intuitive situation towards optional dependencies in providers.

Basically, the idea is that some providers can have dependencies that are **required** for them in order to work properly. But since there is a lot of providers in lexicon, and to avoid to have a software containing a lot of requirements, that would make it harder to integrated, these specifics dependencies are marked as **optional** at the `lexicon` distribution level, with extras defining them.

Here, to make `hetzner` provider working, you should install lexicon with the extra `hetzner`. Something like `pip install dns-lexicon[hetzner]. However, nothing in the lexicon logic make that explicit to you. Indeed, theses dependencies are imported in a `try/except` block: this is done because even if you do not use one particular provider, and so does not require to install its extra, lexicon needs to load all modules to construct the CLI. So this `try/except` block is here only to make the module loadable at all time, but it does not make theses dependencies optional for its related provider.

I have in fact an opened PR, #366, to improve this situation: instead of letting the module be loaded, and explode with cryptic errors when you try to use it, this PR throw instead a custom defined `ProviderNotAvailableError` explaining the situation, and inviting you to install the relevant extra dependencies.

It should be merged soon. I hope this will avoid you and everyone else to suffer from cryptic errors when trying to use this kind of providers. I invite you, since you are concerned by this issue, to check my PR if you want, and make comments about things that could further be improved in your opinion.

**Comment by dgrothaus-ku** [comment]
Hello @adferrand.

Thank's for the fast reply. I did try getting things to work by running `pip install dns-lexicon[hetzner]`, but I think during that time I was juggling around with python 2/3 problems and pip not runnign anymore after upgrading it. So after a fresh restart I forgot to install the additional dependencies again.

The PR #366 describes exactly what I would have expected.

Again, thank you for your time explaining and caring.
