### ISSUE TITLE
Error installing Lexicon on CentOS 7.7.1908

### ISSUE THREAD

**Issue by compusaurusrex** [AnalogJ/lexicon#487]
Hello
I am attempting to install Lexicon on CentOS 7 and getting an error:

Any guidance would be greatly appreciated!

$ sudo pip install git+https://github.com/AnalogJ/lexicon.git#egg=dns-lexicon[full]
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting dns-lexicon[full]
  Cloning https://github.com/AnalogJ/lexicon.git to /tmp/pip-install-hJqIMl/dns-lexicon
  Running command git clone -q https://github.com/AnalogJ/lexicon.git /tmp/pip-install-hJqIMl/dns-lexicon
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hJqIMl/dns-lexicon/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hJqIMl/dns-lexicon/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-hJqIMl/dns-lexicon/pip-egg-info
         cwd: /tmp/pip-install-hJqIMl/dns-lexicon/
    Complete output (5 lines):
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    error in dns-lexicon setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by adferrand** [comment]
It is because the `setuptools` python module installed in your system is ancient, and does not support some of newer features that are used in lexicon configuration. As a quick and dirty way to fix that, I am pretty sure that a good `yum upgrade` will fix your issue. 

But to get the best Python runtime, and since you are on recent version of CentOS (7.7), here what I would do:
1) Install python 3, `yum install -y python3`
2) Create a virtual environment, `python3 -m venv venv
3) Activate it, `source venv/bin/activate`
4) Install lexicon, `pip install dns-lexicon[full] 
5) Profit

As an alternative, the pipx project can avoid you the hassle to handle the virtual environment by yourself: with python3 installed, follow instructions at https://pipxproject.github.io/pipx/, then do `pipx install dns-lexicon[full].

**Comment by compusaurusrex** [comment]
Thanks! I had googled the error, found an article that was similar and solved it by running: 
sudo sudo pip install -U setuptools
I do appreciate the advice though. I am working on a test VM currently; when I deploy a production environment I will follow that advice. Thanks again!

**Comment by adferrand** [comment]
Indeed, your command is installing the latest version of setuptools in user mode. It will work for development, but for production environment, it is better to create a dedicated virtual environment.
