### ISSUE TITLE
gransy doesn't support subdomains

### ISSUE THREAD

**Issue by bilak** [AnalogJ/lexicon#619]
Hi,
I'm trying to write [plugin for certbot](https://github.com/bilak/certbot-dns-gransy) which utilises lexicon. I think that gransy implementation is not working correctly when I'd like to retrieve certificate for subdomain.
So for example if I have domain `example.com` and then some subdomain `test.example.com` as CNAME or any other entry, gransy lexicon fails because it doesn't know such domain. 

```
  File "/Users/lukas/development/python/certbot-dns-gransy/venv/lib/python3.9/site-packages/lexicon/providers/base.py", line 74, in authenticate
    return self._authenticate()
  File "/Users/lukas/development/python/certbot-dns-gransy/venv/lib/python3.9/site-packages/lexicon/providers/gransy.py", line 75, in _authenticate
    raise Exception("Unknown domain {}".format(self.domain))
Exception: Unknown domain test.example.com
```

Problem is that it's trying to lookup only domains and not zones ([probably this endpoint](https://subreg.cz/manual/?cmd=Get_DNS_Zone))

cc: @oldium

**Comment by oldium** [comment]
I am not sure whether you are using it as intended. Please have a look at lexicon/client.py on how it works with subdomains. Lexicon always tries to operate on the main domain.

**Comment by oldium** [comment]
I have checked the certbot code and it depends on the exception being thrown when checking for the correct domain:

https://github.com/certbot/certbot/blob/e570e8ad3230ed5ce24191cde9bbbc6d2a54b630/certbot/certbot/plugins/dns_common_lexicon.py#L82-L116

The problem is that certbot is trying to guess what happened from the error string. This is basically wrong and cannot work generally. [Unfortunately](#204) Lexicon does not have a unified way to report errors, so for now I would stick with the actual implementation.

My recommendation is to add the following method to the `_GransyLexiconClient` class:

```python
     def _handle_general_error(self, e, domain_name):
        if not str(e).startswith('Unknown domain '):
            return errors.PluginError('Unexpected error determining zone identifier for {0}: {1}'
                                      .format(domain_name, e))
        return None
```

**Comment by oldium** [comment]
Please let me know if that worked for you.

**Comment by oldium** [comment]
Ping. Any update?

**Comment by bilak** [comment]
sorry I've missed the notification. I've abandoned the project since I found another solution for my problem.
